---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: car-gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-gateway-service
  template:
    metadata:
      labels:
        app: car-gateway-service
    spec:
      containers:
        - name: car-gateway-service
          image: "redbackracing/car_gateway_service"
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: car-gateway-service-service
spec:
  selector:
    app: car-gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "redbackracing/ui"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /
        backend: 
          service: 
            name: ui-service
            port:
              number: 80
        pathType: Prefix
