---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: car_gateway_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car_gateway_service
  template:
    metadata:
      labels:
        app: car_gateway_service
    spec:
      containers:
        - name: car_gateway_service
          image: "redbackracing/car_gateway_service"
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: car_gateway_service_service
spec:
  selector:
    app: car_gateway_service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui_deployment
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "redbackracing/ui"
---
apiVersion: v1
kind: Service
metadata:
  name: ui_service
  labels:
    app: ui_service
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend: 
          serviceName: ui_service
          servicePort: 80